### ISSUE TITLE
Problem with direct destination and rcp option?

### ISSUE THREAD

**Issue by ottob** [omniti-labs/omnipitr#32]
I tried this and received the following error on my master server (db):
```
2015-09-22 01:15:01.513295 +0000 : 27876 : omnipitr-backup-master : LOG : bash: '!/home/evard/omnipitr/gzip-and-encrypt': No such file or directory
```
Config on db server:
```
-dd evard@gw:/var/backups/postgresql/hot_backup
-rcp '!/home/evard/omnipitr/gzip-and-encrypt'
```

And script on destination server (gw):
```
ottob@gw:~$ ls -l /home/evard/omnipitr/gzip-and-encrypt
-rwx------ 1 evard evard 115 Sep 21 20:38 /home/evard/omnipitr/gzip-and-encrypt
```

I can't figure out whats wrong. Am I missing something obvious?

**Comment by depesz** [comment]
From what I gather you are using config file, and not direct options to omnipitr-backup-master.

In the docs, you can find this paragraph:

> It is important that you don't need to quote the values - value will
> always be up to the end of line (trailing spaces will be removed). So
> if you'd want, for example, to have magic-option set to "/mnt/badly
> named directory", you'd need to quote it when setting from command
> line:
> /some/omnipitr/program --magic-option="/mnt/badly named directory"
> but not in config:
> --magic-option=/mnt/badly named directory

So, the problem seems to be that you quoted value of rcp in your config. Please remove quotes, and retry. If this will not help, please provide whole omnipitr-backup-master command, with all switches, and full content of the config file.

**Comment by ottob** [comment]
Thanks, I will try this and report results tomorrow.

**Comment by ottob** [comment]
Changing the rcp line of the config file to:

`-rcp !/home/evard/omnipitr/gzip-and-encrypt`

fixed the issue. Thanks!
